name: initno_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.3.2
  - cudatoolkit=11.3.1
  - pillow=9.4.0
  - torchvision=0.12.0
  - pip:
    - accelerate==0.26.1
    - albumentations==0.4.3
    - clip
    - diffusers==0.25.1
    - einops==0.3.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - ipywidgets==8.1.0
    - ftfy==6.1.1
    - numpy==1.24.4
    - opencv-python==4.9.0.80
    - omegaconf==2.1.1
    - pudb==2019.2
    - pytorch-lightning==1.4.2
    - test-tube==0.7.5
    - streamlit==1.26.0
    - torch==2.1.2
    - torch-fidelity==0.3.0
    - torchmetrics==0.6.0
    - peft==0.7.1
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - taming-transformers==0.0.1
    - tqdm==4.66.1
    - transformers==4.37.0
    - matplotlib==3.7.3
    - pyrallis==0.3.1
    - jupyter==1.0.0